AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: ceres-reactjs deployment cloudformation script
Globals:
  Function:
    Timeout: 30
Parameters:
  Project:
    Type: String
Resources:
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    DependsOn:
    - S3Bucket
    Properties:
      DistributionConfig:
        Origins:
        - DomainName:
            Fn::Select:
            - 1
            - Fn::Split:
              - //
              - Fn::GetAtt:
                - S3Bucket
                - WebsiteURL
          Id: S3-hosted-website-ID
          CustomOriginConfig:
            OriginProtocolPolicy: http-only
        Enabled: 'true'
        HttpVersion: http2
        DefaultRootObject: index.html
        DefaultCacheBehavior:
          AllowedMethods:
          - GET
          - HEAD
          - OPTIONS
          - PUT
          - PATCH
          - POST
          - DELETE
          TargetOriginId: S3-hosted-website-ID
          ForwardedValues:
            QueryString: 'false'
            Cookies:
              Forward: none
          ViewerProtocolPolicy: redirect-to-https
          DefaultTTL: 0
          MinTTL: 0
          MaxTTL: 0
        PriceClass: PriceClass_200
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:
        Fn::Sub: ${Project}
      WebsiteConfiguration:
        ErrorDocument: index.html
        IndexDocument: index.html
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    DependsOn:
    - S3Bucket
    Properties:
      Bucket:
        Ref: S3Bucket
      PolicyDocument:
        Fn::Join:
        - ''
        - - '{ "Version": "2012-10-17", "Id": "PolicyForCloudFrontPrivateContent",
            "Statement": [ { "Sid": "Allow-OAI-Access-To-Bucket", "Effect": "Allow",
            "Principal": "*", "Action": "s3:GetObject", "Resource": "'
          - Fn::GetAtt:
            - S3Bucket
            - Arn
          - /*" } ] }
